## Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
# import tensorflow
import tensorflow as tf

2023-06-10 17:46:16.877027: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# scaler 
scaler = tf.constant(7)

# vector
vector = tf.constant([3,2])

# matrix
matrix = tf.constant([[3,4],[5,1]])

# tensor
tensor = tf.constant([[[3,4,8],[5,8,3]],[[4,7,8],[8,9,0,]],[[5,2,4],[8,8,0]]])

scaler,vector,matrix,tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[3, 4, 8],
         [5, 8, 3]],
 
        [[4, 7, 8],
         [8, 9, 0]],
 
        [[5, 2, 4],
         [8, 8, 0]]], dtype=int32)>)

## Find the shape, rank and size of the tensors you created in 1.

In [6]:
# shape of tensors
tf.rank(tensor)
tf.rank(vector)
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [8]:
x = tf.range(0,1)

x.normal(shape=[2,3])

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'normal'