<!-- concept of tensor flow -->
## Introdcution to tnsor
Getting infomation from tensor
Manipulating tensors
Tensor and numpy
Usinf @tf.function
Using GPu
Exercises to try

In [2]:
# import tensorflow
import tensorflow as tf

print(tf.__version__)

2.11.0


In [4]:
# create scalar tensor with tf.constant()
scalar = tf.constant(7)
scalar

# check number of dimensions of a tensor
scalar.ndim

0

In [5]:
# create a vector tensor tf.constant()
vector = tf.constant([10,5])

vector

# check number of dimension of a vector tensor
vector.ndim

1

In [6]:
# create a metrix tensor tf.constant()
metrix = tf.constant([[10,5],[0,20]])

metrix

# check number of dimension of a vector tensor
metrix.ndim


2

In [7]:
# create a metrix tensor tf.constant()
metrix2 = tf.constant([[10, 5], [0, 20],[4,6]], dtype=tf.float16)

metrix2

# check number of dimension of a vector tensor
metrix2.ndim


2

In [9]:
# create a tensor tensor
tensor = tf.constant([[[3,4,5],[5,1,8]],[[4,5,6],[2,3,5]],[[45,5,2],[4,1,0]]]) 

tensor

# ckeck number of dymension of tensor

tensor.ndim

3

In [15]:
# changeabletensor with tf.Variable()
var_tensor = tf.Variable([20,8])

var_tensor

# change tensor value
var_tensor[1].assign(3)

var_tensor[1]


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [17]:
# create a random tensors
rand = tf.random.Generator.from_seed(7)

rand.normal(shape=[3,2])


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [21]:
# shuffle random tensor
shuffle = tf.constant([[4,5,6],[6,3,2],[6,7,9]])

tf.random.shuffle(shuffle, seed=32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 7, 9],
       [4, 5, 6],
       [6, 3, 2]], dtype=int32)>

In [35]:
# random seed 
tf.random.set_seed(42) # global level random seed 

tf.random.shuffle(shuffle, seed=42) # operation level rand

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [6, 3, 2],
       [6, 7, 9]], dtype=int32)>

In [36]:
# create tensor of ones
ones = tf.ones([3,4])

ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [46]:
# convert numpy array to tensor
import numpy as np

x = np.arange(0,24, dtype=np.int32)

tf.constant(x)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [48]:
# change a tensor shape

new_tensor = tf.constant(x, shape=(3,8))

new_tensor

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]], dtype=int32)>

In [ ]:
# getting informations from our tensors
